version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip install --upgrade awscli aws-sam-cli
      - npm install -g serverless@1.41.1
      - npm install serverless-domain-manager --save-dev
      - npm install serverless-python-requirements
      - npm install serverless-plugin-canary-deployments --save-dev

  pre_build:
        commands:
          - pip3 install --upgrade virtualenv pytest awscli boto3 botocore moto
          - python3 -m pytest
  
  build:
    commands:
    
  post_build: 
    commands: 
      - pip3 install aws-sam-cli
      - export BUCKET=s3-cloud-pipeline-artifacts
      - aws package --template-file template.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
