version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip3 install awscli --upgrade --user
      - npm install 
  build:
    commands:
      - pip install requests
      - export BUCKET=s3-cloud-pipeline-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
