version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8    
  build:
    commands:
      - sam build 
  post_build:
    commands:
      - pip install --user aws-sam-cli
      - export BUCKET=s3-cloud-pipeline-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
