version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      # Install pip
      - sudo apt-get install python-pip

      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
        
  pre_build:
    commands:
      - python -m unittest discover tests
      
  build:
    commands:
      - sam build 
  post_build:
    commands:
      - pip install --user aws-sam-cli
      - export BUCKET=s3-cloud-pipeline-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
