version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip install --upgrade awscli aws-sam-cli

  build:
    commands:
      - pip3 install aws-sam-cli
      - sam build
      - export BUCKET=s3-cloud-pipeline-artifacts
      - sam package --template-file template.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
