AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for basic-aws-apigateway-lambda function
  
Resources:
    Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod 
      
    Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Role: !GetAtt BasicAWSLambdaRole.Arn
      AutoPublishAlias: DEV
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiResource
      
            
    Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function2.lambda_handler2
      Runtime: python3.8
      Role: !GetAtt BasicAWSLambdaRole.Arn
      AutoPublishAlias: DEV
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref ApiResource
