AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: API
      StageName: Test
      
  Function2:
      Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Role: !GetAtt BasicAWSLambdaRole.Arn
      FunctionName: myfunction-GitHub
      Handler: Lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Description: Invoke lambda function.
      Events:
        APImy:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiResource
            
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Role: !GetAtt BasicAWSLambdaRole.Arn
      FunctionName: myfunction-GitHub2
      Handler: Lambda_function2.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole    
      Events:
        APImy:
          Type: Api
          Properties:
            Path: /lambda_2
            Method: get
            RestApiId: !Ref ApiResource```
 
