AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  basic-aws-apigateway-demo
  Sample SAM Template for basic-aws-apigateway-demo
  
Resources:
  ApiResource:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
       
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiResource
            Path: /
            Method: GET
            
   HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function2.lambda_handler2
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiResource
            Path: /hello
            Method: GET         
    
      
      
