AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      FunctionName: myfunction-GitHub
      Handler: Lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Description: Invoke lambda function.
      Events:
        HelloWorldV2:
          Type: Api
          Properties:
            Path: /
            Method: get
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      FunctionName: myfunction-GitHub2
      Handler: Lambda_function2.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole    
      
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
 
