AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Function and API Gateway creating and deployment
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      FunctionName: myfunction-GitHub
      Handler: dev.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Description: Invoke lambda function.

ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "Users"
      StageName: prod
      Models:
        items:
          type: object
          properties:
            id:
              type: string
            FirstName:
              type: string
            LastName:
              type: string
            Email:
              type: string
            

    
