AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time

Resources:
  ApiResource:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod  
  
  TimeFunction:
    DependsOn:
        - ApiResource
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          LAMBDA_ENVIRONMENT: local
      Events:
        Api:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
            RestApiId: !Ref Api
            
  
  SecondSampleFunction:
    DependsOn:
        - ApiResource
    Type: AWS::Serverless::Function
    Properties:
      Handler: Lambda_function2.lambda_handler2
      Runtime: python3.8
      CodeUri: ./
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          LAMBDA_ENVIRONMENT: local
      Events:
        Api:
          Type: Api
          Properties:
            Path: /TextResource
            Method: GET
            RestApiId: !Ref Api
