AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for basic-aws-apigateway-lambda function
  
Resources:
  provider:
  name: aws
  runtime: python3.8 # Node JS version
  memorySize: 256
  timeout: 15
  stage: dev
  region: eu-central-1 # AWS region
  apiGateway: # Optional API Gateway global config
    restApiId: q46soknj3c # This should be same for the other api being deployed to the same API Gateway
    restApiRootResourceId: uuni865ulk # This should be same for the other api being deployed to the same API Gateway
       
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      AutoPublishAlias: DEV
      DeploymentPreference:
        Type: AllAtOnce 
            
   HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function2.lambda_handler2
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      AutoPublishAlias: DEV
      DeploymentPreference:
        Type: AllAtOnce
